package cnss.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author 
 */
@Entity
@Table(name = "assures")
public class Assure {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user's email
  @NotNull
  private String email;
  
  // The user's name
  @NotNull
  private String nomAssure;
  @Column(name="Pays")
  private String nomPays;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public String getNomAssure() {
	return nomAssure;
}

public void setNomAssure(String nomAssure) {
	this.nomAssure = nomAssure;
}

public String getNomPays() {
	return nomPays;
}

public void setNomPays(String nomPays) {
	this.nomPays = nomPays;
}

public Assure() { }

  public Assure(long id) { 
    this.id = id;
  }
  
  public Assure(String email, String name) {
    this.email = email;
    this.nomAssure = name;
  }

  
  public void setEmail(String value) {
    this.email = value;
  }
  
  public String getName() {
    return nomAssure;
  }

  public void setName(String value) {
    this.nomAssure = value;
  }
  
} // class Assure
